<QuizScreen>:
    name: "quiz"
    MDBoxLayout:
        orientation: "vertical"
        padding: dp(20)
        spacing: dp(15)

        MDLabel:
            id: timer
            text: "30:00"
            halign: "center"
            font_style: "H5"
            theme_text_color: "Primary"
        
        

        MDLabel:
            id: question
            text: "Quiz wird geladen..."
            halign: "center"
            size_hint_y: None
            height: dp(180)
            text_size: self.width, None

        MDTextField:
            id: answer
            hint_text: "Deine Antwort eingeben..."
            multiline: True
            size_hint_y: None
            height: dp(100)

        MDRaisedButton:
            text: "Abschicken"
            pos_hint: {"center_x": .5}
            on_release: root.submit()