<QuizScreen>:
    MDBoxLayout:
        orientation: "vertical"
        padding: dp(20)
        spacing: dp(20)
        md_bg_color: app.theme_cls.primaryColor  # Korrigiert zu primaryColor

        MDTopAppBar:
            title: "QuizScreen"
            md_bg_color: app.theme_cls.primaryColor  # Korrigiert zu primaryColor
            specific_text_color: 1, 1, 1, 1
            pos_hint: {"top": 1}
            anchor_title: "center"

        MDLabel:
            text: "Eingabe Screen"
            halign: "center"