<StatsScreen>:
    MDBoxLayout:
        orientation: "vertical"
        padding: dp(20)
        spacing: dp(20)
        md_bg_color: [1, 1, 1, 1]  # Weißer Hintergrund

        MDTopAppBar:
            title: "Statistiken"
            md_bg_color: [0.0, 0.447, 0.698, 1]  # Blaue TopAppBar
            specific_text_color: [1, 1, 1, 1]  # Weiße Schrift
            pos_hint: {"top": 1}
            anchor_title: "center"

        MDLabel:
            text: "Stats Screen"
            halign: "center"
            text_color: [0, 0, 0, 1]  # Schwarze Schrift