<StatsScreen>:
    name: "stats"
    MDBoxLayout:
        orientation: "vertical"
        padding: dp(20)
        spacing: dp(15)

        MDLabel:
            text: "Dein Lernfortschritt"
            halign: "center"
            font_style: "H5"
            theme_text_color: "Primary"

        MDLabel:
            id: total
            text: "Gesamt: 0 Karten"
            halign: "center"

        ScrollView:
            MDBoxLayout:
                id: stats
                orientation: "vertical"
                size_hint_y: None
                height: self.minimum_height
                spacing: dp(10)
                padding: dp(10)